FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY . .

RUN dotnet restore "Infrastructure.Database.MigrationsRunner/Infrastructure.Database.MigrationsRunner.csproj"

RUN dotnet publish "Infrastructure.Database.MigrationsRunner/Infrastructure.Database.MigrationsRunner.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    /p:UseAppHost=false 

FROM base AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Infrastructure.Database.MigrationsRunner.dll"]