name: Deploy to AWS ECS

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRETS_MANAGER_SECRET_NAME: ${{ secrets.AWS_SECRETS_MANAGER_SECRET_NAME }}
  AWS_ECS_TASK_DEFINITION_FAMILY: ${{ secrets.AWS_ECS_TASK_DEFINITION_FAMILY }}
  AWS_ECS_LOG_GROUP_NAME: ${{ secrets.AWS_ECS_LOG_GROUP_NAME }}
  AWS_ECS_TASK_ROLE_ARN: ${{ secrets.AWS_ECS_TASK_ROLE_ARN }}
  AWS_ECS_TASK_EXECUTION_ROLE_ARN: ${{ secrets.AWS_ECS_TASK_EXECUTION_ROLE_ARN }}
  AWS_SYSTEM_MANAGER_PATH: ${{ secrets.AWS_SYSTEM_MANAGER_PATH }}

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Migrations Runner Image
        working-directory: src/backend/CoreAPI
        run: |
          echo "Building and pushing Docker image to Amazon ECR..."
          echo "${{ github.sha }}"
          IMAGE_TAG=${{ github.sha }}
          
          docker build -t ${{ secrets.AWS_ECR_MIGRATIONS_RUNNER_URI }}:$IMAGE_TAG . -f Dockerfile_migrations
          docker push ${{ secrets.AWS_ECR_MIGRATIONS_RUNNER_URI }}:$IMAGE_TAG
          
          echo "MIGRATIONS_RUNNER_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "MIGRATIONS_RUNNER_DOCKER_IMAGE_URI=${{ secrets.AWS_ECR_MIGRATIONS_RUNNER_URI }}:$IMAGE_TAG" >> $GITHUB_ENV
        
      - name: Create ECS task definition for Migrations Runner
        working-directory: deploy/ecs
        run: |
          envsubst < aspnetcore-migration-runner-task-definition-template.json > aspnetcore-migration-runner-task-definition.json
          
      - name: Run DB migrations
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: deploy/ecs/aspnetcore-migration-runner-task-definition.json
          cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
          run-task: true
          wait-for-task-stopped: true
          run-task-subnets: ${{ secrets.AWS_SUBNETS }}
          run-task-security-groups: ${{ secrets.AWS_SECURITY_GROUPS }}
          run-task-assign-public-IP: ENABLED
      
      - name: Build & Push Docker image
        working-directory: src/backend/CoreAPI
        run: |
          echo "Building and pushing Docker image to Amazon ECR..."
          echo "${{ github.sha }}"
          IMAGE_TAG=${{ github.sha }}
          
          docker build -t ${{ secrets.AWS_ECR_API_URI }}:$IMAGE_TAG . -f Dockerfile_api
          docker push ${{ secrets.AWS_ECR_API_URI }}:$IMAGE_TAG
          
          echo "API_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "API_DOCKER_IMAGE_URI=${{ secrets.AWS_ECR_API_URI }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Create ECS task definition for API service
        working-directory: deploy/ecs
        run: |
          envsubst < aspnetcore-task-definition-template.json > aspnetcore-task-definition.json

      - name: Deploy API service to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: deploy/ecs/aspnetcore-task-definition.json
          service: ${{ secrets.AWS_ECS_SERVICE_NAME }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Create frontend env file
        working-directory: src/frontend
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.production

      - name: Build react app
        working-directory: src/frontend
        run: |
          npm ci
          npm run build:prod

      - name: Sync to s3
        working-directory: src/frontend
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete --cache-control "public, max-age=0, must-revalidate"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"