name: Deploy to AWS ECS

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_GITHUB_OIDC_ROLE_ARN: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
  AWS_SECRETS_MANAGER_SECRET_NAME: ${{ secrets.AWS_SECRETS_MANAGER_SECRET_NAME }}
  AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
  AWS_ECS_CLUSTER_NAME: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
  AWS_ECS_SERVICE_NAME: ${{ secrets.AWS_ECS_SERVICE_NAME }}
  AWS_ECS_TASK_DEFINITION_FAMILY: ${{ secrets.AWS_ECS_TASK_DEFINITION_FAMILY }}
  AWS_ECS_TASK_DEFINITION_DESIRED_COUNT: ${{ secrets.AWS_ECS_TASK_DEFINITION_DESIRED_COUNT }}
  AWS_ECS_LOG_GROUP_NAME: ${{ secrets.AWS_ECS_LOG_GROUP_NAME }}
  AWS_ECS_TASK_ROLE_ARN: ${{ secrets.AWS_ECS_TASK_ROLE_ARN }}
  AWS_ECS_TASK_EXECUTION_ROLE_ARN: ${{ secrets.AWS_ECS_TASK_EXECUTION_ROLE_ARN }}
  AWS_SUBNETS: ${{ secrets.AWS_SUBNETS }}
  AWS_SECURITY_GROUPS: ${{ secrets.AWS_SECURITY_GROUPS }}
  AWS_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        working-directory: src/backend/CoreAPI
        run: |
          run: |
          echo "Building and pushing Docker image to Amazon ECR..."
          echo "${{ github.sha }}"
          IMAGE_TAG=${{ github.sha }}
          
          docker build -t ${{ env.AWS_ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ env.AWS_ECR_REPOSITORY }}:$IMAGE_TAG
          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_URI=${{ env.AWS_ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Generate ECS task definition
        working-directory: deploy/ecs
        run: |
          envsubst < aspnetcore-task-definition-template.json > aspnetcore-task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: deploy/ecs/aspnetcore-task-definition.json
          service: ${{ env.AWS_ECS_SERVICE_NAME }}
          cluster:  ${{ env.AWS_ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          